"use client";
import { useEffect,useState } from "react";
const demo={reservation_date:"2026-10-10",reservation_time:"19:30",party_size:4,customer_name:"María Rodríguez",customer_phone:"300 000 0000",created_at:"2026-10-07T14:30:00-05:00",status:"pending"};
export default function ReservasPage(){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[settings,setSettings]=useState<any>(null);
 useEffect(()=>{Promise.all([fetch("/api/admin/requests").then(r=>r.json()),fetch("/api/admin/settings").then(r=>r.json())]).then(([a,b])=>{setRows(a.reservations||[]);setSettings(b.settings?.reservations||{})}).finally(()=>setLoading(false))},[]);
 const emptyMessage=settings?.no_active_message||"No hay reservas activas en este momento.";
 return <main className="admin-page"><section className="admin-head"><p className="eyebrow">MESA</p><h1>Reservas</h1><p>Consulta las solicitudes. La confirmación y conversación continúan por WhatsApp.</p></section>
 <section className="admin-table-card">{loading?<p className="admin-empty">Cargando solicitudes…</p>:rows.length===0?<><div className="admin-empty"><strong>{emptyMessage}</strong><p>No hay reservas reales que consultar ahora mismo.</p></div><div className="admin-example-card"><span>EJEMPLO DE REFERENCIA</span><h3>Así se verá una reserva cuando llegue</h3><div className="admin-example-grid"><div><small>FECHA</small><strong>10 oct 2026</strong></div><div><small>HORA</small><strong>7:30 p. m.</strong></div><div><small>PERSONAS</small><strong>4</strong></div><div><small>SOLICITANTE</small><strong>{demo.customer_name}</strong><small>{demo.customer_phone}</small></div></div><em>Este registro es ilustrativo y no está guardado como reserva real.</em></div></>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Fecha</th><th>Hora</th><th>Personas</th><th>Solicitud</th><th>Recibida</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td>{r.reservation_date||r.date||"—"}</td><td>{r.reservation_time||r.time||"—"}</td><td>{r.party_size||r.guests||"—"}</td><td><strong>{r.customer_name||r.name||"—"}</strong><small>{r.customer_phone||r.phone||""}</small></td><td>{r.created_at?new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",timeStyle:"short"}).format(new Date(r.created_at)):"—"}</td></tr>)}</tbody></table></div>}</section></main>;
}