"use client";
import { useEffect,useState } from "react";
import { useLanguage } from "@/components/language-provider";
export default function ReservationsPage(){
 const {lang}=useLanguage();const en=lang==="EN";const [requested,setRequested]=useState(false),[people,setPeople]=useState("2"),[config,setConfig]=useState<any>(null),[name,setName]=useState(""),[phone,setPhone]=useState("");
 useEffect(()=>{fetch("/api/public/settings").then(r=>r.json()).then(d=>setConfig(d.settings||{})).catch(()=>{})},[]);
 const reservations=config?.reservations||{enabled:true,large_party_threshold:5,cancellation_cutoff_hours:2,no_active_message:"No hay reservas activas en este momento."};const wa=config?.whatsapp||{phone:"+573156771482",message:"Hola, quiero comunicarme con Andariegos."};const threshold=Number(reservations.large_party_threshold||5);const disabled=reservations.enabled===false;const message=`Hola Andariegos, soy ${name||"un cliente"} y quiero solicitar una reserva para ${people} personas.`;
 return <main className="inner-page"><section className="inner-hero compact"><p className="eyebrow">{en?"TABLE":"MESA"}</p><h1>{en?"Reservations":"Reservas"}</h1><p>{en?"Send the request and Andariegos confirms it by WhatsApp. Requests remain pending until the restaurant confirms.":"Envía la solicitud y Andariegos la confirma por WhatsApp. La reserva queda pendiente hasta que el restaurante la confirme."}</p></section>
 <section className="section reservation-layout"><div className="reservation-card">{disabled?<><span className="success-mark">—</span><h2>{en?"Reservations are currently unavailable.":"No hay reservas activas en este momento."}</h2><p>{en?"Please contact Andariegos directly by WhatsApp.":"Puedes contactar directamente a Andariegos por WhatsApp."}</p></>:!requested?<><label>{en?"People":"Personas"}<select value={people} onChange={e=>setPeople(e.target.value)}>{Array.from({length:Math.max(12,threshold)},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label>{Number(people)>threshold&&<p className="form-error">{en?`For more than ${threshold} people, contact the restaurant directly.`:`Para grupos de más de ${threshold} personas, contacta directamente al restaurante.`}</p>}<label>{en?"Date":"Fecha"}<input type="date"/></label><label>{en?"Time":"Hora"}<input type="time"/></label><label>{en?"Name":"Nombre"}<input value={name} onChange={e=>setName(e.target.value)} placeholder={en?"Your name":"Tu nombre"}/></label><label>{en?"Phone":"Teléfono"}<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder={en?"WhatsApp number":"Número de WhatsApp"}/></label><button className="button button-primary full-button" disabled={Number(people)>threshold||!name||!phone} onClick={()=>setRequested(true)}>{en?"REQUEST RESERVATION":"SOLICITAR RESERVA"}</button></>:<><span className="success-mark">✓</span><h2>{en?"Ready to send.":"Lista para enviar."}</h2><p>{en?"The request remains pending until Andariegos confirms it by WhatsApp.":"La solicitud queda pendiente hasta que Andariegos la confirme por WhatsApp."}</p><a className="button button-primary full-button" target="_blank" rel="noreferrer" href={`https://wa.me/${String(wa.phone||"").replace(/\D/g,"")}?text=${encodeURIComponent(message)}`}>{en?"SEND TO ANDARIEGOS":"ENVIAR A ANDARIEGOS"}</a><button className="button full-button" onClick={()=>setRequested(false)}>{en?"EDIT":"EDITAR"}</button></>}</div>
 <aside className="reservation-notes"><p className="eyebrow">{en?"GOOD TO KNOW":"PARA TENER EN CUENTA"}</p><h2>{en?"A request is not a confirmation.":"Solicitar no es confirmar."}</h2><p>{en?"The restaurant confirms by WhatsApp.":"El restaurante confirma por WhatsApp."}</p><p>{en?`For groups over ${threshold} people, contact the restaurant directly.`:`Para grupos de más de ${threshold} personas, contacta directamente al restaurante.`}</p><p>{en?`Changes and cancellations should be requested at least ${reservations.cancellation_cutoff_hours||2} hours before.`:`Los cambios y cancelaciones deben solicitarse con al menos ${reservations.cancellation_cutoff_hours||2} horas de anticipación.`}</p></aside></section></main>;
}
