"use client";
import { useState } from "react";
import { useLanguage } from "@/components/language-provider";
export default function ReservationsPage(){
  const {lang}=useLanguage(); const en=lang==="EN"; const [requested,setRequested]=useState(false); const [people,setPeople]=useState("2");
  const message=`Hola Andariegos, quiero solicitar una reserva para ${people} personas.`;
  return <main className="inner-page"><section className="inner-hero compact"><p className="eyebrow">{en?"TABLE":"MESA"}</p><h1>{en?"Reservations":"Reservas"}</h1><p>{en?"Send the request and Andariegos confirms it by WhatsApp. Requests remain pending until the restaurant confirms.":"Envía la solicitud y Andariegos la confirma por WhatsApp. La reserva queda pendiente hasta que el restaurante la confirme."}</p></section>
    <section className="section reservation-layout"><div className="reservation-card">{!requested?<><label>{en?"People":"Personas"}<select value={people} onChange={e=>setPeople(e.target.value)}>{Array.from({length:12},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label><label>{en?"Date":"Fecha"}<input type="date"/></label><label>{en?"Time":"Hora"}<input type="time"/></label><label>{en?"Name":"Nombre"}<input placeholder={en?"Your name":"Tu nombre"}/></label><label>{en?"Phone":"Teléfono"}<input placeholder={en?"WhatsApp number":"Número de WhatsApp"}/></label><button className="button button-primary full-button" onClick={()=>setRequested(true)}>{en?"REQUEST RESERVATION":"SOLICITAR RESERVA"}</button></>:<><span className="success-mark">✓</span><h2>{en?"Ready to send.":"Lista para enviar."}</h2><p>{en?"The final flow will send the summary to WhatsApp and show that the request is pending confirmation.":"El flujo final enviará el resumen por WhatsApp y mostrará que la solicitud queda pendiente de confirmación."}</p><a className="button button-primary full-button" target="_blank" rel="noreferrer" href={`https://wa.me/573242870766?text=${encodeURIComponent(message)}`}>{en?"SEND TO ANDARIEGOS":"ENVIAR A ANDARIEGOS"}</a><button className="button full-button" onClick={()=>setRequested(false)}>{en?"EDIT":"EDITAR"}</button></>}</div>
      <aside className="reservation-notes"><p className="eyebrow">{en?"GOOD TO KNOW":"PARA TENER EN CUENTA"}</p><h2>{en?"A request is not a confirmation.":"Solicitar no es confirmar."}</h2><p>{en?"The restaurant confirms by WhatsApp, preferably within 24 hours.":"El restaurante confirma por WhatsApp, preferiblemente dentro de 24 horas."}</p><p>{en?"For groups over 12 people, contact the restaurant directly.":"Para grupos de más de 12 personas, contacta directamente al restaurante."}</p><p>{en?"Changes and cancellations are handled through WhatsApp.":"Cambios y cancelaciones se gestionan por WhatsApp."}</p></aside></section>
  </main>;
}
