"use client";
import { useEffect,useState } from "react";
import { useSearchParams } from "next/navigation";
export default function EditarContenido(){
 const params=useSearchParams(),id=params.get("id"),draft=params.get("draft");const [title,setTitle]=useState(""),[titleEn,setTitleEn]=useState(""),[text,setText]=useState(""),[textEn,setTextEn]=useState(""),[status,setStatus]=useState("draft"),[when,setWhen]=useState(""),[image,setImage]=useState(""),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(id)fetch("/api/admin/content").then(r=>r.json()).then(d=>{const x=(d.content?.highlights||[]).find((v:any)=>v.id===id);if(x){setTitle(x.title_es||"");setTitleEn(x.title_en||"");setText(x.description_es||"");setTextEn(x.description_en||"");setStatus(x.status||"draft");setWhen(x.publish_at?new Date(x.publish_at).toISOString().slice(0,16):"");setImage(x.image_url||"")}});else if(draft){const t=[{e:"Una mesa para quedarse",en:"A table worth staying for",d:"Una invitación a conocer Andariegos, comer sin afán y descubrir Simijaca.",de:"An invitation to discover Andariegos, eat without rushing and discover Simijaca."},{e:"Cocinas de otros mundos",en:"Cuisines from other worlds",d:"Historias, platos de autor e ingredientes que traen otros lugares hasta nuestra mesa.",de:"Stories, signature dishes and ingredients that bring other places to our table."},{e:"Ven a descubrir Simijaca",en:"Come discover Simijaca",d:"Una escapada de sabor para quienes quieren conocer el municipio y quedarse un rato.",de:"A flavorful escape for people who want to discover the town and stay awhile."}][Number(draft)];if(t){setTitle(t.e);setTitleEn(t.en);setText(t.d);setTextEn(t.de)}}},[id,draft]);
 async function upload(file:File){setError("");if(localStorage.getItem("andariegos-demo")==="1"){setImage(URL.createObjectURL(file));return}const form=new FormData();form.append("file",file);const r=await fetch("/api/admin/media",{method:"POST",body:form});const d=await r.json();if(!r.ok){setError(d.error||"No fue posible subir la imagen.");return}setImage(d.url)}
 async function save(){setSaving(true);setError("");try{const current=await fetch("/api/admin/content").then(r=>r.json());let list=current.content?.highlights||[];const item={id:id||crypto.randomUUID(),title_es:title,title_en:titleEn||title,description_es:text,description_en:textEn||text,image_url:image||null,status,publish_at:when?new Date(when).toISOString():null};list=id?list.map((x:any)=>x.id===id?item:x):[...list,item];const r=await fetch("/api/admin/content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({highlights:list})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No fue posible guardar.");setSaved(true)}catch(e){setError(e instanceof Error?e.message:"No fue posible guardar.")}finally{setSaving(false)}}
 return <main className="admin-page"><section className="admin-head"><p className="eyebrow">MARCA</p><h1>{id?"Editar destacado":"Nuevo destacado"}</h1><p>Sube una imagen, escribe el contenido y decide si sale ahora, queda en borrador o se programa.</p></section><section className="admin-config-card"><div className="admin-form-grid"><label>Título ES<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ej. Ven a conocer Simijaca"/></label><label>Título EN<input value={titleEn} onChange={e=>setTitleEn(e.target.value)} placeholder="Example: Come discover Simijaca"/></label><label>Texto ES<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Una historia breve que invite a conocer Andariegos."/></label><label>Texto EN<textarea value={textEn} onChange={e=>setTextEn(e.target.value)} placeholder="A short story inviting people to discover Andariegos."/></label><label>Estado<select value={status} onChange={e=>setStatus(e.target.value)}><option value="draft">Borrador</option><option value="published">Publicar ahora</option><option value="scheduled">Programar</option></select></label>{status==="scheduled"&&<label>Publicar el<input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/></label>}<label className="admin-form-span-2">Imagen<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/><small>JPG, PNG, WebP, GIF y otros formatos de imagen compatibles. Máximo 5 MB.</small></label></div>{image&&<div className="admin-upload-frame"><img src={image} alt="Vista previa del contenido"/></div>}{error&&<p className="admin-modal-error">{error}</p>}<button className="button button-primary" onClick={save} disabled={saving}>{saving?"GUARDANDO…":id?"GUARDAR CAMBIOS":"GUARDAR DESTACADO"}</button>{saved&&<p className="admin-note">Guardado correctamente.</p>}</section></main>;
}
