"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
export default function ContenidoPage(){
 const [items,setItems]=useState<any[]>([]),[loading,setLoading]=useState(true);
 const load=()=>fetch("/api/admin/content").then(r=>r.json()).then(d=>setItems(d.content?.highlights||[])).finally(()=>setLoading(false));
 useEffect(()=>{load()},[]);
 async function remove(id:string){const next=items.filter(x=>x.id!==id);const r=await fetch("/api/admin/content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({highlights:next})});if(r.ok)setItems(next)}
 return <main className="admin-page"><section className="admin-head"><p className="eyebrow">MARCA</p><h1>Contenido</h1><p>Historias, destacados y promociones para que más personas conozcan Andariegos y quieran visitarlo.</p></section><section className="admin-content-list"><div className="admin-section-heading"><div><p className="eyebrow">BIBLIOTECA</p><h2>Destacados</h2></div><Link className="button button-primary" href="/admin/contenido/editar">NUEVO DESTACADO</Link></div>{loading?<p className="admin-empty">Cargando…</p>:items.length===0?<p className="admin-empty">Todavía no hay destacados. Empieza con una historia, una promoción o una invitación a conocer Simijaca.</p>:items.map((x:any)=><article key={x.id} className="admin-content-item admin-content-item-rich">{x.image_url?<img src={x.image_url} alt=""/>:<div className="admin-content-placeholder">SIN IMAGEN</div>}<div><span>{String(x.status||"draft").toUpperCase()}</span><h3>{x.title_es||"Sin título"}</h3><p>{x.description_es||"Sin descripción"}</p>{x.publish_at&&<small>Publicación: {new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",timeStyle:"short"}).format(new Date(x.publish_at))}</small>}<div className="admin-content-item-actions"><Link className="admin-inline-button" href={`/admin/contenido/editar?id=${encodeURIComponent(x.id)}`}>EDITAR</Link><button className="admin-inline-button danger" onClick={()=>remove(x.id)}>ELIMINAR</button></div></div></article>)}</section></main>;
}
