"use client";
import { useEffect,useState } from "react";
type Item={product_name_es:string;product_name_en?:string;quantity:number;unit_price_cop:number;line_total_cop?:number};
type Order={id:string;order_number:number;customer_name:string;customer_phone:string;delivery_type:string;address:string|null;address_reference?:string|null;payment_method_id:string;subtotal_cop:number;delivery_fee_cop:number;total_cop:number;notes:string|null;created_at:string;order_items?:Item[]};
const money=(n:number)=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(n);
const date=(v:string)=>new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
export default function PedidosPage(){
 const [orders,setOrders]=useState<Order[]>([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Order|null>(null);
 useEffect(()=>{fetch("/api/admin/orders").then(r=>r.json()).then(d=>setOrders(d.orders||[])).finally(()=>setLoading(false))},[]);
 const filtered=orders.filter(o=>[o.customer_name,o.customer_phone,String(o.order_number)].join(" ").toLowerCase().includes(q.toLowerCase()));
 return <main className="admin-page"><section className="admin-head"><p className="eyebrow">OPERACIÓN</p><h1>Pedidos</h1><p>Consulta lo que llegó. La coordinación del pedido continúa por WhatsApp.</p></section>
 <section className="admin-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por nombre, celular o pedido…"/><span>{filtered.length} pedidos</span></section>
 <section className="admin-table-card">{loading?<p className="admin-empty">Cargando pedidos…</p>:filtered.length===0?<p className="admin-empty">No encontramos pedidos con esa búsqueda.</p>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Entrega</th><th>Total</th><th>Recibido</th></tr></thead><tbody>{filtered.map(o=><tr key={o.id} className="admin-clickable-row" onClick={()=>setSelected(o)}><td><strong>AND-{String(o.order_number).padStart(4,"0")}</strong></td><td><span>{o.customer_name}</span><small>{o.customer_phone}</small></td><td>{o.delivery_type==="delivery"?"Domicilio":"Recoger"}</td><td><strong>{money(o.total_cop)}</strong></td><td>{date(o.created_at)}</td></tr>)}</tbody></table></div>}</section>
 {selected&&<div className="admin-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><section className="admin-modal admin-modal-modern"><div className="admin-modal-header"><div><p className="eyebrow">DETALLE DEL PEDIDO</p><h2>AND-{String(selected.order_number).padStart(4,"0")}</h2><p>{selected.customer_name} · {selected.customer_phone}</p></div><button className="admin-modal-close" onClick={()=>setSelected(null)}>×</button></div><div className="admin-order-detail">{(selected.order_items||[]).map((item,i)=><div className="admin-order-detail-line" key={i}><div><strong>{item.quantity} × {item.product_name_es}</strong><small>{money(item.unit_price_cop)} cada uno</small></div><b>{money(item.line_total_cop??item.unit_price_cop*item.quantity)}</b></div>)}<div className="admin-order-detail-total"><span>Subtotal</span><b>{money(selected.subtotal_cop)}</b></div><div className="admin-order-detail-total"><span>Domicilio</span><b>{money(selected.delivery_fee_cop)}</b></div><div className="admin-order-detail-total grand"><span>Total</span><b>{money(selected.total_cop)}</b></div><div className="admin-order-meta"><span>ENTREGA</span><strong>{selected.delivery_type==="delivery"?selected.address||"Domicilio sin dirección": "Recoger en Andariegos"}</strong>{selected.address_reference&&<small>{selected.address_reference}</small>}<span>PAGO</span><strong>{selected.payment_method_id}</strong>{selected.notes&&<><span>NOTAS</span><strong>{selected.notes}</strong></>}</div></div></section></div>}
 </main>;
}