'use client';
import {useMemo,useState} from 'react';
type P={id:string;c:string;n:string;d:string;i:string;p:number};
const P:P[]=[
['sim','Entradas','SIMIJACA','Papa chorreada','Papa, preparación de la casa',8500],['taq','Entradas','TÁQUIRA','Tortilla de queso','Queso, tortilla',14500],['sal','Entradas','SALITRE','Deditos de queso','Queso, masa artesanal',13500],['rafa','Entradas','SAN RAFAEL','Queso asado','Queso',11500],['pinos','Entradas','LOS PINOS','Pastel de yuca','Yuca, relleno de la casa',3500],['lope','Entradas','DON LOPE','Arepitas de quinoa','Quinoa, maíz',10500],
['cris','Pizzas','CRISTALES','Pizza napolitana','Masa, tomate, queso',19000],['junc','Pizzas','JUNCAL','Pizza de champiñones','Champiñones, masa, queso',19000],['fical','Pizzas','FICAL','Pizza de piña dulce','Piña, masa, queso',19000],['esp','Pizzas','ESPERANZA','Pizza mexicana','Vegetales, sabores mexicanos, queso',19000],['moy','Pizzas','MOYBA','Pizza de orellanas','Orellanas, masa, queso',19000],['apo','Pizzas','APOSENTOS','Pizza de vegetales asados','Vegetales asados, masa, queso',19000],['ceb','Pizzas','PIZZA DE CEBOLLA','Cebolla caramelizada','Cebolla, masa, queso',19000],
['sc','Hamburguesas','SAN CAYETANO','Hamburguesa de frijol','Frijol, pan, vegetales',20000],['sb','Hamburguesas','SANTA BÁRBARA','Hamburguesa de lentejas','Lentejas, pan, vegetales',20000],['lc','Hamburguesas','LAS CHATAS','Mini hamburguesitas','Preparación vegetal, pan',13500],
['pb','Arepas','PEÑA BLANCA','Arepa de acompañado','Arepa, acompañamientos de la casa',13500],['ret','Mazorcada','EL RETÉN','Omelette relleno de mazorcada','Huevo, maíz, vegetales',13500],
['susa','Cocina del Mundo','SUSA','Ramen','Fideos, vegetales, caldo',24000],['chi','Cocina del Mundo','CHIQUINQUIRÁ','Lasagna','Pasta, salsa, vegetales, queso',25000],['uba','Cocina del Mundo','UBATÉ','Carne de hongos','Hongos, salsa de la casa',24000],['raq','Cocina del Mundo','RÁQUIRA','Arroz frito','Arroz, vegetales',24000],['pv','Cocina del Mundo','PUEBLO VIEJO','Milanesa de berenjena a la parmesana','Berenjena, tomate, parmesano',24000],['and','Cocina del Mundo','ANDAREGO','Sandwich','Pan, vegetales, preparación de la casa',19000],['vr','Cocina del Mundo','VILLA REAL','Fettuccini caseros','Pasta fresca, salsa de la casa',23500],
['alto','Postres de autor','ALTO AMARILLO','Crème brûlée','Crema, vainilla, azúcar',9000],['pied','Postres de autor','PIEDRA COLADA','Panqueque de arequipe','Panqueque, arequipe',12500],['par','Postres de autor','PARAÍSO','Helado casero','Preparación casera',9500],['cue','Postres de autor','CUEVA NEGRA','Volcán de chocolate','Chocolate, preparación de la casa',12000],
['sic','Jugos','SICUARA','Manzana + pepino + jengibre','Manzana, pepino, jengibre',4500],['tuy','Jugos','TUYA','Mango + pepino + jengibre','Mango, pepino, jengibre',4500],['run','Jugos','RUNGA','Mora + hierbabuena','Mora, hierbabuena',4500],['luc','Jugos','SANTA LUCÍA','Naranja + zanahoria + jengibre','Naranja, zanahoria, jengibre',4500],['mar','Jugos','LA MARÍA','Piña + hierbabuena o pepino + jengibre','Piña, hierbabuena, pepino, jengibre',4500],['marg','Jugos','LAS MARGARITAS','Limonada + hierbabuena + jengibre','Limón, hierbabuena, jengibre',4500]
].map(x=>({id:x[0] as string,c:x[1] as string,n:x[2] as string,d:x[3] as string,i:x[4] as string,p:x[5] as number}));
const money=(n:number)=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n);
export default function Menu(){const[q,setQ]=useState('');const[cart,setCart]=useState<Record<string,number>>({});const[show,setShow]=useState(false);const f=useMemo(()=>P.filter(x=>`${x.n} ${x.d} ${x.i}`.toLowerCase().includes(q.toLowerCase())),[q]);const groups=f.reduce<Record<string,P[]>>((a,x)=>{(a[x.c]??=[]).push(x);return a},{});const count=Object.values(cart).reduce((a,b)=>a+b,0);const total=P.reduce((a,x)=>a+(cart[x.id]??0)*x.p,0);const add=(id:string)=>setCart(c=>({...c,[id]:(c[id]??0)+1}));const sub=(id:string)=>setCart(c=>{const n={...c};n[id]=(n[id]??1)-1;if(n[id]<=0)delete n[id];return n});const text=P.filter(x=>cart[x.id]).map(x=>`${cart[x.id]} x ${x.n}`).join('%0A');return <main className="menu-page"><section className="menu-head"><p className="eyebrow">ANDARIEGOS</p><h1>Menú</h1><p>Busca por plato o ingrediente. Agrega y arma tu pedido sin vueltas.</p><div className="menu-tools"><label className="search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar plato o ingrediente..."/></label><button className="cart-pill" onClick={()=>setShow(true)}>🛒 {count}</button></div></section>{Object.entries(groups).map(([g,items])=><section className="category" key={g}><div className="cat-title"><h2>{g}</h2><span>{items.length}</span></div><div className="products">{items.map(x=><article className="product" key={x.id}><div className="product-art">✦</div><div className="product-body"><div className="product-name"><h3>{x.n}</h3><strong>{money(x.p)}</strong></div><p>{x.d}</p><small>{x.i}</small><button onClick={()=>add(x.id)}>{cart[x.id]?`AGREGAR · ${cart[x.id]}`:'AGREGAR'}</button></div></article>)}</div></section>)}{show&&<div className="overlay" onClick={()=>setShow(false)}><aside className="cart" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShow(false)}>×</button><p className="eyebrow">TU PEDIDO</p><h2>Carrito</h2>{!count?<p className="empty">Tu carrito está esperando algo rico. 🍃</p>:<><div>{P.filter(x=>cart[x.id]).map(x=><div className="line" key={x.id}><span><b>{x.n}</b><small>{money(x.p)} c/u</small></span><span><button onClick={()=>sub(x.id)}>−</button> {cart[x.id]} <button onClick={()=>add(x.id)}>+</button></span></div>)}</div><div className="total"><span>Total</span><b>{money(total)}</b></div><a className="btn primary full" target="_blank" href={`https://wa.me/573242870766?text=Hola%20Andariegos%2C%20quiero%20hacer%20este%20pedido%3A%0A${text}%0A%0ATotal%20estimado%3A%20${encodeURIComponent(money(total))}`}>ENVIAR A ANDARIEGOS</a><p className="micro">Esto inicia la solicitud por WhatsApp; la confirmación la realiza Andariegos.</p></>}</aside></div>}</main>}
