"use client";
import { useEffect,useState } from "react";
const money=(n:number)=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(n);
export default function ClientesPage(){
 const [customers,setCustomers]=useState<any[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(""),[selected,setSelected]=useState<any|null>(null),[reveal,setReveal]=useState(false);
 useEffect(()=>{fetch("/api/admin/customers").then(r=>r.json()).then(d=>setCustomers(d.customers||[])).finally(()=>setLoading(false))},[]);
 const filtered=customers.filter(c=>[c.name,c.phone,String(c.topItem||"")].join(" ").toLowerCase().includes(q.toLowerCase()));
 const orders=customers.reduce((n,c)=>n+Number(c.orders||0),0),spend=customers.reduce((n,c)=>n+Number(c.total||0),0),frequent=customers.slice().sort((a,b)=>Number(b.orders)-Number(a.orders))[0];
 return <main className="admin-page"><section className="admin-head"><p className="eyebrow">RELACIÓN</p><h1>Clientes</h1><p>Una vista rápida para entender qué está pasando con las personas que ya interactuaron con Andariegos.</p></section><div className="admin-summary-grid"><article className="admin-summary-card"><span>CLIENTES</span><strong>{customers.length}</strong><small>registros encontrados</small></article><article className="admin-summary-card"><span>PEDIDOS</span><strong>{orders}</strong><small>en el historial consultado</small></article><article className="admin-summary-card"><span>CONSUMO</span><strong>{money(spend)}</strong><small>COP acumulados</small></article><article className="admin-summary-card"><span>MÁS FRECUENTE</span><strong>{frequent?.orders||0}</strong><small>pedidos · podio principal</small></article></div><section className="admin-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente, celular o plato…"/><span>{filtered.length} clientes</span></section><section className="admin-table-card">{loading?<p className="admin-empty">Cargando…</p>:filtered.length===0?<p className="admin-empty">No encontramos clientes con esa búsqueda.</p>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Cliente</th><th>Pedidos</th><th>Consumo</th><th>Favorito</th><th>Último movimiento</th></tr></thead><tbody>{filtered.map(c=><tr key={c.key} className="admin-clickable-row" onClick={()=>{setSelected(c);setReveal(false)}}><td><strong>{reveal&&selected?.key===c.key?c.name:c.maskedName}</strong><small>{reveal&&selected?.key===c.key?c.phone:"Datos protegidos · entrar para ver"}</small></td><td>{c.orders}</td><td>{money(c.total)}</td><td>{c.topItem||"—"}</td><td>{new Intl.DateTimeFormat("es-CO",{dateStyle:"medium"}).format(new Date(c.last))}</td></tr>)}</tbody></table></div>}</section>
 {selected&&<div className="admin-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><section className="admin-modal admin-modal-modern"><div className="admin-modal-header"><div><p className="eyebrow">CLIENTE</p><h2>{reveal?selected.name:selected.maskedName}</h2><p>{reveal?selected.phone:"Datos protegidos por defecto"}</p></div><button className="admin-modal-close" onClick={()=>setSelected(null)}>×</button></div><div className="admin-customer-detail"><button className="admin-reveal-button" onClick={()=>setReveal(v=>!v)}>{reveal?"OCULTAR DATOS":"VER DATOS"}</button><div className="admin-customer-stats"><span><b>{selected.orders}</b> pedidos</span><span><b>{money(selected.total)}</b> consumo</span><span><b>{selected.topItem||"—"}</b> favorito</span></div><h3>Historial de pedidos</h3>{selected.history.map((o:any)=><div className="admin-history-row" key={o.id}><div><strong>AND-{String(o.order_number).padStart(4,"0")}</strong><small>{new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",timeStyle:"short"}).format(new Date(o.created_at))}</small></div><b>{money(o.total)}</b><span>{(o.items||[]).map((i:any)=>`${i.quantity} × ${i.product_name_es}`).join(" · ")}</span></div>)}</div></section></div>}
 </main>;
}
