"use client";
import Link from "next/link";
import { useCart } from "@/components/cart-provider";
import { formatCOP } from "@/lib/menu-data";
import { useLanguage } from "@/components/language-provider";
export default function CheckoutPage(){
  const {items,total,add,remove,count,clear,summaryText}=useCart(); const {lang}=useLanguage(); const en=lang==="EN";
  const whatsapp=`https://wa.me/573242870766?text=${encodeURIComponent(`${en?"Hello Andariegos, I would like to make this order:":"Hola Andariegos, quiero hacer este pedido:"}\n${summaryText}\n\n${en?"Estimated total":"Total estimado"}: ${formatCOP(total)}`)}`;
  return <main className="checkout-page"><section className="checkout-shell"><div className="checkout-heading"><p className="eyebrow">{en?"YOUR ORDER":"TU PEDIDO"}</p><h1>{en?"Ready when you are.":"Listo cuando tú estés."}</h1><p>{en?"This is the shared cart for the whole site.":"Este es el carrito compartido por todo el sitio."}</p></div>
    {!count?<div className="empty-checkout"><div className="empty-symbol">🍃</div><h2>{en?"Your cart is empty.":"Tu carrito está vacío."}</h2><p>{en?"You can open it from anywhere. For now, let's find something good.":"Puedes abrirlo desde cualquier parte. Por ahora, vamos a buscar algo rico."}</p><Link className="button button-primary" href="/menu">{en?"GO TO MENU":"IR AL MENÚ"}</Link></div>
    :<div className="checkout-grid"><div className="order-card"><div className="order-card-head"><h2>{en?"Your selection":"Tu selección"}</h2><button onClick={clear}>{en?"Clear":"Vaciar"}</button></div>{items.map(({product,quantity})=><div className="order-line" key={product.id}><div><b>{product.name}</b><small>{product.description}</small></div><div className="order-qty"><button onClick={()=>remove(product.id)}>−</button><b>{quantity}</b><button onClick={()=>add(product.id)}>+</button></div><strong>{formatCOP(product.price*quantity)}</strong></div>)}<div className="order-total"><span>{en?"Estimated total":"Total estimado"}</span><b>{formatCOP(total)}</b></div></div>
      <aside className="request-card"><p className="eyebrow">{en?"NEXT STEP":"SIGUIENTE PASO"}</p><h2>{en?"Send the request to Andariegos.":"Envía la solicitud a Andariegos."}</h2><p>{en?"WhatsApp is where the restaurant confirms the order and shares payment instructions.":"WhatsApp es donde el restaurante confirma el pedido y comparte las instrucciones de pago."}</p><a className="button button-primary full-button" href={whatsapp} target="_blank" rel="noreferrer">{en?"SEND TO ANDARIEGOS":"ENVIAR A ANDARIEGOS"}</a><p className="microcopy">{en?"This does not confirm the order automatically.":"Esto inicia la solicitud; no confirma automáticamente el pedido."}</p><div className="checkout-note"><b>{en?"Delivery":"Domicilios"}</b><span>{en?"Own delivery service · provisional fee $5,000 · radius 5 km.":"Servicio propio · tarifa provisional $5.000 · radio de 5 km."}</span></div><div className="checkout-note"><b>{en?"Payments":"Pagos"}</b><span>Nequi · Daviplata · Bre-B/llave · efectivo.</span></div></aside></div>}
  </section></main>;
}
