"use client";

import { useEffect,useState } from "react";

export default function NuevoProducto(){
 const [cats,setCats]=useState<any[]>([]); const [name,setName]=useState(""); const [nameEn,setNameEn]=useState(""); const [price,setPrice]=useState(""); const [cat,setCat]=useState(""); const [status,setStatus]=useState("available"); const [image,setImage]=useState(""); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/admin/menu").then(r=>r.json()).then(d=>setCats(d.categories||[]))},[]);
 async function upload(file:File){if(localStorage.getItem("andariegos-demo")==="1"){setImage(URL.createObjectURL(file));return}const form=new FormData();form.append("file",file);const r=await fetch("/api/admin/media",{method:"POST",body:form});const d=await r.json();if(r.ok)setImage(d.url);else setMessage(d.error||"No fue posible subir la imagen.")}
 async function save(){setSaving(true);setMessage("");const r=await fetch("/api/admin/menu",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name_es:name,name_en:nameEn,price_cop:price,category_id:cat,status,image_url:image})});const d=await r.json();setMessage(r.ok?"Producto creado correctamente.":d.error||"No fue posible guardar.");setSaving(false)}
 return <main className="admin-page"><section className="admin-head"><p className="eyebrow">CARTA</p><h1>Nuevo producto</h1><p>Agrega un plato sin tocar código. La misma información alimenta el menú público.</p></section><section className="admin-config-card"><div className="admin-form-grid"><label>Nombre ES<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Ramen de la casa"/></label><label>Nombre EN<input value={nameEn} onChange={e=>setNameEn(e.target.value)} placeholder="House ramen"/></label><label>Precio COP<input inputMode="numeric" value={price} onChange={e=>setPrice(e.target.value)} placeholder="24000"/></label><label>Categoría<select value={cat} onChange={e=>setCat(e.target.value)}><option value="">Selecciona una</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name_es}</option>)}</select></label><label>Estado<select value={status} onChange={e=>setStatus(e.target.value)}><option value="available">Disponible</option><option value="soon">Próximamente</option><option value="soldout">Agotado</option></select></label><label>Fotografía<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/></label></div>{image&&<img className="admin-upload-preview" src={image} alt="Vista previa"/>}<button className="button button-primary" onClick={save} disabled={saving}>{saving?"GUARDANDO…":"CREAR PRODUCTO"}</button>{message&&<p className="admin-note">{message}</p>}</section></main>;
}
