"use client";
import Image from "next/image";
import Link from "next/link";
import { useLanguage } from "@/components/language-provider";
export default function SimijacaPage(){
  const {lang}=useLanguage(); const en=lang==="EN";
  return <main className="inner-page"><section className="inner-hero"><span className="floating-doodle">🍃</span><p className="eyebrow">DESPUÉS DEL PLATO</p><h1>Simijacá</h1><p>{en?"There is a reason to come to Simijacá: discover Andariegos. And once you came to Andariegos, discover Simijacá.":"Hay una razón para venir a Simijacá: descubrir Andariegos. Y ya que viniste a Andariegos, descubre Simijacá."}</p></section>
    <section className="section route-section"><div className="route-copy"><span>01</span><h2>{en?"A plan can start with hunger.":"Un plan puede empezar con hambre."}</h2><p>{en?"Before or after eating, the town can become part of the experience: a walk, a coffee, a place to stay or simply a slower afternoon.":"Antes o después de comer, el pueblo puede convertirse en parte de la experiencia: una caminata, un café, un lugar donde quedarse o simplemente una tarde más despacio."}</p></div><div className="route-note"><b>BOGOTÁ · UBATÉ · CHIQUINQUIRÁ · BARBOSA</b><span>{en?"Come from wherever you are.":"Llega desde donde estés."}</span></div></section>
    <section className="root-story"><div className="root-image"><Image src="/images/masterchef-simijaca.jpeg" alt="Plato de Andariegos" fill sizes="(max-width: 800px) 100vw, 50vw"/></div><div className="root-copy"><p className="eyebrow">HOMENAJE A LA RAÍZ</p><h2>{en?"A dish can carry a place with it.":"Un plato también puede llevar un lugar consigo."}</h2>{en?<p>To the root, to the land of grandfather Neftalí, to the Simijacense forest, to Moiba and Las Lajas, to the hands that work the corn, to the garden, to family, memory and the people who left a mark. A gift and a tribute to beautiful Simijacá.</p>:<><p>Este plato es un homenaje a la raíz, a la tierra del abuelo Neftalí, un homenaje al bosque Simijense, a Moiba, a las Lajas y a las manos que trabajan el maíz.</p><p>A la genética, que como herencia, cocinera hoy recae sobre mí; a la huerta de don tata, de cata, al quesito de la vaca, al cobijo de la mamá, a la papa y a la ruana.</p><p>Este plato es mi regalo y mi homenaje para ti, mi bella Simijacá.</p></>}</div></section>
    <section className="section stay-section"><p className="eyebrow">PLAN DE FIN DE SEMANA</p><h2>{en?"Eat. Walk. Stay. Return.":"Comer. Caminar. Quedarse. Volver."}</h2><p>{en?"This section will grow with practical local recommendations: places to walk, stay and visit, always keeping Andariegos as the starting point.":"Esta sección crecerá con recomendaciones locales útiles: dónde caminar, quedarse y visitar, siempre con Andariegos como punto de partida."}</p><div className="plan-grid"><article><span>01</span><i>🥕</i><h3>{en?"Before lunch":"Antes de comer"}</h3><p>{en?"A slow arrival to town.":"Llegar sin afán al pueblo."}</p></article><article><span>02</span><i>🍅</i><h3>{en?"At the table":"En la mesa"}</h3><p>{en?"Let the menu do the traveling.":"Dejar que la carta haga el viaje."}</p></article><article><span>03</span><i>🍃</i><h3>{en?"After lunch":"Después de comer"}</h3><p>{en?"Keep discovering Simijacá.":"Seguir descubriendo Simijacá."}</p></article></div></section>
    <section className="invitation-section compact-invitation"><h2>{en?"We invite you to make the trip.":"Te invitamos a hacer el viaje."}</h2><Link className="button button-primary" href="/menu">{en?"BACK TO ANDARIEGOS":"VOLVER A ANDARIEGOS"}</Link></section>
  </main>;
}
