"use client";
import {useEffect,useState} from "react";
type C={id:string;name_es:string;name_en:string};type P={id:string;category_id:string;name_es:string;name_en:string;description_es:string;description_en:string;ingredients_es:string;ingredients_en:string;price_cop:number;image_url:string|null;status:string;is_spicy:boolean;is_featured:boolean;categories?:C|null};type I={id:string;name_es:string;quantity:number;unit:string;soldout_until:string|null};
const money=(n:number)=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(n);
export default function MenuAdminPage(){const[p,setP]=useState<P[]>([]),[c,setC]=useState<C[]>([]),[i,setI]=useState<I[]>([]),[q,setQ]=useState(""),[edit,setEdit]=useState<P|null>(null),[img,setImg]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[invSaving,setInvSaving]=useState(false),[msg,setMsg]=useState("");
useEffect(()=>{Promise.all([fetch("/api/admin/menu").then(r=>r.json()),fetch("/api/admin/inventory").then(r=>r.json())]).then(([m,v])=>{setP(m.products||[]);setC(m.categories||[]);setI(v.items||[])}).finally(()=>setLoading(false))},[]);
const list=p.filter(x=>(x.name_es+" "+x.name_en).toLowerCase().includes(q.toLowerCase()));
const open=(x:P)=>{setEdit({...x});setImg(x.image_url||"");setMsg("")};
async function upload(f:File){if(localStorage.getItem("andariegos-demo")==="1"){setImg(URL.createObjectURL(f));return}const fd=new FormData();fd.append("file",f);const r=await fetch("/api/admin/media",{method:"POST",body:fd});const d=await r.json();if(r.ok)setImg(d.url);else setMsg(d.error||"No fue posible subir la imagen.")}
async function save(){if(!edit)return;setSaving(true);const r=await fetch("/api/admin/menu",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...edit,image_url:img||null})});const d=await r.json();if(r.ok){setP(a=>a.map(x=>x.id===edit.id?{...x,...edit,image_url:img||null}:x));setEdit(null)}else setMsg(d.error||"No fue posible guardar.");setSaving(false)}
async function saveInv(){setInvSaving(true);const r=await fetch("/api/admin/inventory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:i})});const d=await r.json();setMsg(r.ok?"Inventario guardado y enlazado al menú.":d.error||"No fue posible guardar.");setInvSaving(false)}
return <main className="admin-page"><section className="admin-head"><p className="eyebrow">CARTA</p><h1>Menú</h1><p>Productos, precios, imágenes, disponibilidad e inventario.</p></section>
<section className="admin-menu-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar producto…"/><a className="button button-primary" href="/admin/menu/nuevo">NUEVO PRODUCTO</a></section>
<section className="admin-config-card"><div className="admin-section-heading"><div><p className="eyebrow">PRODUCTOS</p><h2>{list.length} productos</h2></div><span className="admin-section-note">Selecciona para editar</span></div>{loading?<p className="admin-empty">Cargando…</p>:<div className="admin-product-grid">{list.map(x=><button type="button" className="admin-product-card" key={x.id} onClick={()=>open(x)}><div className="admin-product-thumb">{x.image_url?<img src={x.image_url} alt=""/>:<span>SIN FOTO</span>}</div><div className="admin-product-card-body"><small>{x.categories?.name_es||"Sin categoría"}</small><h3>{x.name_es}</h3><span>{x.name_en}</span><strong>{money(x.price_cop)}</strong><em className={"admin-status-chip "+x.status}>{x.status==="available"?"Disponible":x.status==="soldout"?"Agotado":x.status==="soon"?"Próximamente":"Oculto"}</em></div></button>)}</div>}</section>
<section className="admin-config-card"><div className="admin-section-heading"><div><p className="eyebrow">INVENTARIO</p><h2>Ingredientes y existencias</h2><p>Cantidad 0 bloquea los productos relacionados en la web.</p></div></div><div className="admin-inventory-grid">{i.map((x,n)=><div className={"admin-inventory-item "+(x.quantity<=0?"is-empty":"")} key={x.id}><div><strong>{x.name_es}</strong><small>{x.unit}</small></div><div className="admin-inventory-controls"><input type="number" min="0" value={x.quantity} onChange={e=>setI(a=>a.map((z,j)=>j===n?{...z,quantity:Number(e.target.value)}:z))}/><button type="button" onClick={()=>setI(a=>a.map((z,j)=>j===n?{...z,quantity:0}:z))}>{x.quantity<=0?"AGOTADO":"AGOTAR"}</button></div><label>Agotado hasta<input type="datetime-local" value={x.soldout_until?new Date(x.soldout_until).toISOString().slice(0,16):""} onChange={e=>setI(a=>a.map((z,j)=>j===n?{...z,soldout_until:e.target.value?new Date(e.target.value).toISOString():null}:z))}/></label></div>)}</div><button className="button button-primary" onClick={saveInv} disabled={invSaving}>{invSaving?"GUARDANDO…":"GUARDAR INVENTARIO"}</button>{msg&&<p className="admin-note">{msg}</p>}</section>
{edit&&<div className="admin-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setEdit(null)}><section className="admin-modal admin-modal-modern admin-product-editor"><div className="admin-modal-header"><h2>Editar {edit.name_es}</h2><button className="admin-modal-close" onClick={()=>setEdit(null)}>×</button></div><div className="admin-product-editor-layout"><div><div className="admin-product-editor-image">{img?<img src={img} alt=""/>:<span>SIN IMAGEN</span>}</div><div className="admin-image-actions"><label className="button">CAMBIAR IMAGEN<input hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/></label><button className="button" onClick={()=>setImg("")}>QUITAR</button></div></div><div className="admin-form-grid"><label>Nombre ES<input value={edit.name_es} onChange={e=>setEdit({...edit,name_es:e.target.value})}/></label><label>Nombre EN<input value={edit.name_en} onChange={e=>setEdit({...edit,name_en:e.target.value})}/></label><label>Precio COP<input inputMode="numeric" value={edit.price_cop} onChange={e=>setEdit({...edit,price_cop:Number(e.target.value)||0})}/></label><label>Categoría<select value={edit.category_id} onChange={e=>setEdit({...edit,category_id:e.target.value})}>{c.map(x=><option key={x.id} value={x.id}>{x.name_es}</option>)}</select></label><label>Estado<select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}><option value="available">Disponible</option><option value="soon">Próximamente</option><option value="soldout">Agotado</option><option value="hidden">Oculto</option></select></label><label className="admin-toggle-row"><input type="checkbox" checked={!!edit.is_featured} onChange={e=>setEdit({...edit,is_featured:e.target.checked})}/> Destacado</label><label className="admin-form-span-2">Descripción ES<textarea value={edit.description_es||""} onChange={e=>setEdit({...edit,description_es:e.target.value})}/></label><label className="admin-form-span-2">Descripción EN<textarea value={edit.description_en||""} onChange={e=>setEdit({...edit,description_en:e.target.value})}/></label><label>Ingredientes ES<textarea value={edit.ingredients_es||""} onChange={e=>setEdit({...edit,ingredients_es:e.target.value})}/></label><label>Ingredientes EN<textarea value={edit.ingredients_en||""} onChange={e=>setEdit({...edit,ingredients_en:e.target.value})}/></label></div></div><div className="admin-modal-actions"><button className="button" onClick={()=>setEdit(null)}>CANCELAR</button><button className="button button-primary" onClick={save} disabled={saving}>{saving?"GUARDANDO…":"GUARDAR PRODUCTO"}</button></div>{msg&&<p className="admin-modal-error">{msg}</p>}</section></div>}</main>}