"use client";
import { useEffect,useState } from "react";
type Product={id:string;name_es:string;name_en:string;price_cop:number;status:string;image_url:string|null;is_featured:boolean;ingredients_es?:string};
const money=(n:number)=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(n);
const demoIngredients=[["Champiñones",7,"unidad"],["Tomates",12,"unidad"],["Cebolla",9,"unidad"],["Ajo",18,"unidad"],["Queso",6,"porción"],["Masa de pizza",10,"unidad"],["Carne",8,"porción"],["Pollo",11,"porción"],["Arroz",9,"porción"],["Fideos",14,"porción"],["Arepas",16,"unidad"],["Papa",24,"unidad"]];
export default function MenuAdminPage(){
 const [products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(""),[editing,setEditing]=useState<Product|null>(null),[inventory,setInventory]=useState<any[]>([]),[invSaving,setInvSaving]=useState(false),[message,setMessage]=useState("");
 const load=()=>fetch("/api/admin/menu").then(r=>r.json()).then(d=>setProducts(d.products||[])).finally(()=>setLoading(false));
 useEffect(()=>{load();fetch("/api/admin/inventory").then(r=>r.json()).then(d=>setInventory(d.items?.length?d.items:demoIngredients.map((x,i)=>({id:"demo-"+i,name_es:x[0],quantity:x[1],unit:x[2],active:true})))})).catch(()=>setInventory(demoIngredients.map((x,i)=>({id:"demo-"+i,name_es:x[0],quantity:x[1],unit:x[2],active:true}))))},[]);
 const list=products.filter(p=>(p.name_es+" "+p.name_en).toLowerCase().includes(q.toLowerCase()));
 async function status(id:string,status:string){const r=await fetch("/api/admin/menu",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});if(r.ok)setProducts(ps=>ps.map(p=>p.id===id?{...p,status}:p))}
 async function saveProduct(){if(!editing)return;const r=await fetch("/api/admin/menu",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing)});if(r.ok){setProducts(ps=>ps.map(p=>p.id===editing.id?editing:p));setEditing(null)}}
 async function saveInventory(){setInvSaving(true);const r=await fetch("/api/admin/inventory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:inventory})});const d=await r.json();setMessage(r.ok?(d.demo?"Inventario de ejemplo actualizado en DEMO.":"Inventario guardado."):d.error||"No fue posible guardar.");setInvSaving(false)}
 return <main className="admin-page">
  <section className="admin-head"><p className="eyebrow">CARTA</p><h1>Menú</h1><p>Mantén lo que ofrecemos: productos, precios, ingredientes, imágenes y disponibilidad.</p></section>
  <section className="admin-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar producto…"/><a className="button button-primary" href="/admin/menu/nuevo">NUEVO PRODUCTO</a></section>
  <section className="admin-table-card"><div className="admin-section-heading"><div><p className="eyebrow">PRODUCTOS</p><h2>Disponibilidad</h2></div><span className="admin-section-note">{list.length} productos</span></div>{loading?<p className="admin-empty">Cargando menú…</p>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Producto</th><th>Precio</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{list.map(p=><tr key={p.id} onClick={()=>setEditing(p)} className="admin-clickable-row"><td><strong>{p.name_es}</strong><small>{p.name_en}</small></td><td>{money(p.price_cop)}</td><td><span className={"admin-status-chip "+p.status}>{p.status==="available"?"Disponible":p.status==="soldout"?"Agotado":p.status==="soon"?"Próximamente":"Oculto"}</span></td><td><button className="admin-inline-button" onClick={e=>{e.stopPropagation();status(p.id,p.status==="soldout"?"available":"soldout")}}>{p.status==="soldout"?"REACTIVAR":"AGOTAR"}</button></td></tr>)}</tbody></table></div>}</section>
  <section className="admin-config-card"><div className="admin-section-heading"><div><p className="eyebrow">INVENTARIO</p><h2>Ingredientes y existencias</h2><p>Los números son una base editable de ejemplo. Cámbialos por las cantidades reales.</p></div></div><div className="admin-inventory-grid">{inventory.map((x,i)=><label key={x.id||i} className="admin-inventory-item"><span>{x.name_es}</span><div><input type="number" min="0" value={x.quantity} onChange={e=>setInventory(a=>a.map((it,j)=>j===i?{...it,quantity:Number(e.target.value)}:it))}/><small>{x.unit}</small></div><button type="button" className={Number(x.quantity)<=0?"is-empty":""} onClick={()=>setInventory(a=>a.map((it,j)=>j===i?{...it,quantity:0}:it))}>{Number(x.quantity)<=0?"AGOTADO":"MARCAR AGOTADO"}</button></label>)}</div><button className="button button-primary" onClick={saveInventory} disabled={invSaving}>{invSaving?"GUARDANDO…":"GUARDAR INVENTARIO"}</button>{message&&<p className="admin-note">{message}</p>}</section>
  {editing&&<div className="admin-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setEditing(null)}><section className="admin-modal admin-modal-modern"><div className="admin-modal-header"><div><p className="eyebrow">PRODUCTO</p><h2>Editar {editing.name_es}</h2></div><button className="admin-modal-close" onClick={()=>setEditing(null)}>×</button></div><div className="admin-form-grid"><label>Nombre ES<input value={editing.name_es} onChange={e=>setEditing({...editing,name_es:e.target.value})}/></label><label>Nombre EN<input value={editing.name_en} onChange={e=>setEditing({...editing,name_en:e.target.value})}/></label><label>Precio COP<input inputMode="numeric" value={editing.price_cop} onChange={e=>setEditing({...editing,price_cop:Number(e.target.value)})}/></label><label>Estado<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option value="available">Disponible</option><option value="soon">Próximamente</option><option value="soldout">Agotado</option><option value="hidden">Oculto</option></select></label><label className="admin-form-span-2">Ingredientes<textarea value={editing.ingredients_es||""} onChange={e=>setEditing({...editing,ingredients_es:e.target.value})} placeholder="Ej. champiñones, cebolla, queso…"/></label></div><div className="admin-modal-actions"><button className="button button-secondary" onClick={()=>setEditing(null)}>CANCELAR</button><button className="button button-primary" onClick={saveProduct}>GUARDAR PRODUCTO</button></div></section></div>}
 </main>;
}
