"use client";
import { useEffect,useState } from "react";
type Settings=Record<string,any>;
const fallback={restaurant:{timezone:"America/Bogota",schedule:{monday:null,tuesday:null,wednesday:{open:"12:00",close:"21:00"},thursday:{open:"12:00",close:"21:00"},friday:{open:"12:00",close:"21:00"},saturday:{open:"12:00",close:"21:00"},sunday:{open:"12:00",close:"21:00"}},special_closure:{active:false,reason:null,message:null,starts_at:null,ends_at:null}},delivery:{enabled:true,radius_km:5,fee_cop:5000,method:"own_delivery"},whatsapp:{phone:"+573156771482",name:"Andariegos WhatsApp",message:"Hola, quiero comunicarme con Andariegos."},reservations:{enabled:true,large_party_threshold:5,cancellation_cutoff_hours:2,no_active_message:"No hay reservas activas en este momento."},page_content:{home:{hero_es:"Cocinas de otros mundos a tu mundo.",hero_en:"Cuisines from other worlds, to your world.",hero_note_es:"Platos de autor, ingredientes frescos y una invitación a sentarte sin afán.",hero_note_en:"Author dishes, fresh ingredients and an invitation to sit down without rushing."},highlights:[]}};
const money=(n:number)=>new Intl.NumberFormat("es-CO").format(n);
export default function ConfiguracionPage(){
 const [settings,setSettings]=useState<Settings>(fallback),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[demo,setDemo]=useState(false);
 useEffect(()=>{const demoMode=localStorage.getItem("andariegos-demo")==="1";setDemo(demoMode);fetch("/api/admin/settings").then(r=>r.json()).then(d=>{const base={...fallback,...d.settings};const stored=demoMode?localStorage.getItem("andariegos-demo-settings"):null;setSettings(stored?JSON.parse(stored):base)}).finally(()=>setLoading(false))},[]);
 const patch=(section:string,key:string,value:any)=>setSettings(s=>({...s,[section]:{...s[section],[key]:value}}));
 async function save(){setSaving(true);setMessage("");try{const r=await fetch("/api/admin/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({settings})});const d=await r.json();if(!r.ok)throw new Error(d.error||"No fue posible guardar.");if(demo){localStorage.setItem("andariegos-demo-settings",JSON.stringify(settings));setMessage("Guardado solo en MODO DEMO. No se modificó la plataforma real.");}else{setSettings(d.settings);setMessage("Cambios guardados. La web pública usa esta configuración.")}}catch(e){setMessage(e instanceof Error?e.message:"No fue posible guardar.")}finally{setSaving(false)}}
 const delivery=settings.delivery||fallback.delivery,wa=settings.whatsapp||fallback.whatsapp,res=settings.reservations||fallback.reservations,home=settings.page_content?.home||fallback.page_content.home;
 if(loading)return <main className="admin-page"><section className="admin-head"><h1>Configuración</h1><p>Cargando configuración…</p></section></main>;
 return <main className="admin-page">
  <section className="admin-head"><p className="eyebrow">SISTEMA</p><div className="admin-title-row"><div><h1>Configuración</h1><p>Todo lo que cambia el comportamiento de la web, sin tocar código.</p></div>{demo&&<span className="admin-demo-badge">DEMO · LOS CAMBIOS NO SON REALES</span>}</div></section>
  <section className="admin-config-card"><div className="admin-section-heading"><div><p className="eyebrow">RESTAURANTE</p><h2>Horario semanal</h2><p>Este es el horario normal. Las aperturas y cierres excepcionales se controlan en Inicio.</p></div></div>
   <div className="admin-schedule-editor">{Object.entries((settings.restaurant||{}).schedule||{}).map(([day,v]:any)=><div className="admin-schedule-row" key={day}><strong>{day==="monday"?"Lunes":day==="tuesday"?"Martes":day==="wednesday"?"Miércoles":day==="thursday"?"Jueves":day==="friday"?"Viernes":day==="saturday"?"Sábado":"Domingo"}</strong>{v?<><input type="time" value={v.open} onChange={e=>setSettings(s=>({...s,restaurant:{...s.restaurant,schedule:{...s.restaurant.schedule,[day]:{...v,open:e.target.value}}}})}/><span>—</span><input type="time" value={v.close} onChange={e=>setSettings(s=>({...s,restaurant:{...s.restaurant,schedule:{...s.restaurant.schedule,[day]:{...v,close:e.target.value}}}})}/><button type="button" onClick={()=>setSettings(s=>({...s,restaurant:{...s.restaurant,schedule:{...s.restaurant.schedule,[day]:null}}}))}>CERRAR</button></>:<button type="button" onClick={()=>setSettings(s=>({...s,restaurant:{...s.restaurant,schedule:{...s.restaurant.schedule,[day]:{open:"12:00",close:"21:00"}}}}))}>ABRIR</button>}</div>)}</div>
  </section>
  <section className="admin-config-grid">
   <article className="admin-config-card"><span>DOMICILIOS</span><h2>Servicio propio</h2><label className="admin-config-field">Tarifa COP<input inputMode="numeric" value={delivery.fee_cop??5000} onChange={e=>patch("delivery","fee_cop",Number(e.target.value)||0)}/></label><label className="admin-config-field">Radio máximo (km)<input type="number" min="0" step=".5" value={delivery.radius_km??5} onChange={e=>patch("delivery","radius_km",Number(e.target.value)||0)}/></label><label className="admin-toggle-row"><input type="checkbox" checked={delivery.enabled!==false} onChange={e=>patch("delivery","enabled",e.target.checked)}/> Domicilios activos</label></article>
   <article className="admin-config-card"><span>WHATSAPP</span><h2>{wa.name||"Andariegos WhatsApp"}</h2><label className="admin-config-field">Nombre visible<input value={wa.name||""} onChange={e=>patch("whatsapp","name",e.target.value)} placeholder="Ej. Andariegos WhatsApp"/></label><label className="admin-config-field">Número<input value={wa.phone||""} onChange={e=>patch("whatsapp","phone",e.target.value)} placeholder="+57…"/></label><label className="admin-config-field">Mensaje inicial<textarea value={wa.message||""} onChange={e=>patch("whatsapp","message",e.target.value)} placeholder="Hola, quiero comunicarme con Andariegos." rows={3}/></label></article>
   <article className="admin-config-card"><span>RESERVAS</span><h2>{res.enabled===false?"Inactivas":"Activas"}</h2><label className="admin-config-field">Máximo antes de contacto directo<input type="number" min="1" value={res.large_party_threshold??5} onChange={e=>patch("reservations","large_party_threshold",Number(e.target.value)||1)}/></label><label className="admin-config-field">Cancelación (horas)<input type="number" min="0" value={res.cancellation_cutoff_hours??2} onChange={e=>patch("reservations","cancellation_cutoff_hours",Number(e.target.value)||0)}/></label><label className="admin-config-field">Mensaje sin reservas<textarea value={res.no_active_message||""} onChange={e=>patch("reservations","no_active_message",e.target.value)} rows={3}/></label><label className="admin-toggle-row"><input type="checkbox" checked={res.enabled!==false} onChange={e=>patch("reservations","enabled",e.target.checked)}/> Reservas activas</label></article>
  </section>
  <section className="admin-config-card"><span>PÁGINA</span><h2>Textos del Home</h2><div className="admin-form-grid"><label>Frase principal ES<input value={home.hero_es||""} onChange={e=>setSettings(s=>({...s,page_content:{...s.page_content,home:{...home,hero_es:e.target.value}}}))}/></label><label>Frase principal EN<input value={home.hero_en||""} onChange={e=>setSettings(s=>({...s,page_content:{...s.page_content,home:{...home,hero_en:e.target.value}}}))}/></label><label>Descripción ES<textarea value={home.hero_note_es||""} onChange={e=>setSettings(s=>({...s,page_content:{...s.page_content,home:{...home,hero_note_es:e.target.value}}}))}/></label><label>Descripción EN<textarea value={home.hero_note_en||""} onChange={e=>setSettings(s=>({...s,page_content:{...s.page_content,home:{...home,hero_note_en:e.target.value}}}))}/></label></div></section>
  <div className="admin-save-bar"><button className="button button-primary" onClick={save} disabled={saving}>{saving?"GUARDANDO…":"GUARDAR CAMBIOS"}</button>{message&&<span>{message}</span>}</div>
 </main>;
}
